version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fishing-chat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - chat-network

  postgres:
    image: postgres:15
    container_name: fishing-chat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fishing_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data:
