services:
  # Database
  postgres:
    image: postgres:15
    container_name: fishing-chat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fishing_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Message Queue는 Amazon MQ로 이전됨
  # 기존 RabbitMQ 컨테이너 제거

  # Backend API
  chat-api:
    build:
      context: ./chat-api
      dockerfile: Dockerfile
    container_name: fishing-chat-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fishing_chat
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_PROFILES_ACTIVE=docker

      # - SPRING_RABBITMQ_HOST=b-12345678-1234-1234-1234-123456789012.mq.ap-northeast-2.amazonaws.com
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5671
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=password123
      - SPRING_RABBITMQ_SSL_ENABLED=false
      - SPRING_RABBITMQ_VIRTUAL_HOST=/
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chat-network
    restart: unless-stopped

  # Frontend Web
  web:
    image: 859727769026.dkr.ecr.ap-northeast-2.amazonaws.com/fishing-booking-web:latest
    container_name: fishing-chat-web
    ports:
      - "80:3000"
    depends_on:
      - chat-api
    networks:
      - chat-network
    restart: unless-stopped

networks:
  chat-network:
    driver: bridge

volumes:
  postgres_data:
