name: Deploy to AWS ECR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
  CHAT_API_REPOSITORY: fishing-booking-chat-api
  WEB_REPOSITORY: fishing-booking-web

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      chat-api: ${{ steps.changes.outputs.chat-api }}
      web: ${{ steps.changes.outputs.web }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            chat-api:
              - 'chat-api/**'
            web:
              - 'web/**'

  deploy-chat-api:
    needs: detect-changes
    if: needs.detect-changes.outputs.chat-api == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push chat-api image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd chat-api
          docker build -t $ECR_REGISTRY/$CHAT_API_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$CHAT_API_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$CHAT_API_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$CHAT_API_REPOSITORY:latest

  deploy-web:
    needs: detect-changes
    if: needs.detect-changes.outputs.web == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push web image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd web
          docker build -t $ECR_REGISTRY/$WEB_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$WEB_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$WEB_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$WEB_REPOSITORY:latest
